version: '3.1'
services:
  web:
    build:
      context: web/.
      args:
        - WEB_PORT=${DOTENV_WEB_PORT}
        - API_HOST=http://${DOTENV_API_HOST}:${DOTENV_API_PORT}
    image: petersonwsantos/web-stone
    ports:
      - "${DOTENV_WEB_PORT}:${DOTENV_WEB_PORT}"
    environment:
      - WEB_PORT=${DOTENV_WEB_PORT}
      - API_HOST=http://${DOTENV_API_HOST}:${DOTENV_API_PORT}
  api:
    build:
      context: api/.
      args:
        - API_PORT=${DOTENV_API_PORT}
        - API_DB=postgres://stone:stone@db:5432/stone
    image: petersonwsantos/api-stone
    ports:
      - "${DOTENV_API_PORT}:${DOTENV_API_PORT}"
    environment:
     - API_DB=postgres://${DOTENV_POSTGRES_USER}:${DOTENV_POSTGRES_PASSWORD}@{DOTENV_POSTGRES_HOST}/${DOTENV_POSTGRES_DB}
     - API_PORT=${DOTENV_API_PORT}
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DOTENV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOTENV_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DOTENV_POSTGRES_DB}
